# Docker Deployment Template
- name: Build Docker image
  run: |
    docker build -t myapp:latest .

- name: Push Docker image (if using registry)
  run: |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker tag myapp:latest myregistry.com/myapp:latest
    docker push myregistry.com/myapp:latest
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

