# S3 Deployment Template
- name: Deploy to AWS S3
  run: |
    aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }} --delete
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}
