name: Generate GitHub Workflow

on:
  push:
    branches: [main]
    paths:
      - '**/*.java'
      - '.ci/**'
    
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      #workflows: write

          
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install pyyaml

      - name: Generate workflow
        run: python .ci/generate_workflow.py

      - name: Commit generated workflow
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/generated.yml
          git commit -m "Auto-generate GitHub Actions workflow" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GEN }}@github.com/${{ github.repository }}.git HEAD:main


