name: Java CI/CD

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: manual-approval
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: mvn test

# Docker Deployment Template
- name: Build Docker image
  run: |
    docker build -t myapp:latest .

- name: Push Docker image (if using registry)
  run: |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker tag myapp:latest myregistry.com/myapp:latest
    docker push myregistry.com/myapp:latest
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

